# This project follows the Ribose OSS style guide.
# https://github.com/riboseinc/oss-guides
# All project-specific additions and overrides should be specified in this file.

inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

# Local repo-specific modifications
AllCops:
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3
Rails:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/TrailingCommaInArguments:
  Exclude:
    # RSpec expectations can easily go multiline.  And sometimes, it's all not
    # about multiple arguments, but more about & or | operators.  Comma placed
    # after a single method argument which spans across many lines is confusing,
    # not helpful.  Hence, I'm disabling this cop for all specs.
    - "spec/**/*"
